
# Archivo: src/robot_val.kv

<RobotMelantia>:
    canvas.before:
        PushMatrix
        Rotate:
            angle: root.angulo_pensando
            origin: self.center
            
    canvas:
        # 1. Cuerpo base (Círculo liviano)
        Color:
            rgba: 0.15, 0.15, 0.15, 1
        Ellipse:
            pos: self.pos
            size: self.size

        # 2. Ojos de Valentina (Brillan cuando habla)
        Color:
            rgba: (0, 1, 0.8, root.brillo_ojos) # Cyan esmeralda
        Ellipse: # Ojo izquierdo
            pos: self.x + self.width * 0.28, self.y + self.height * 0.45
            size: self.width * 0.12, self.height * 0.12
        Ellipse: # Ojo derecho
            pos: self.x + self.width * 0.6, self.y + self.height * 0.45
            size: self.width * 0.12, self.height * 0.12

        # 3. Toque Femenino (Moño/Lazo Rosa)
        Color:
            rgba: (1, 0.4, 0.7, 1) # Color rosa
        # Dibujamos un lazo simple con dos triángulos (puntos)
        Triangle:
            points: [self.x + self.width*0.7, self.y + self.height*0.8, self.x + self.width*0.85, self.y + self.height*0.9, self.x + self.width*0.85, self.y + self.height*0.7]

    canvas.after:
        PopMatrix
